server:
  port: 8090


keycloak:
  server-url: http://localhost:8080
  realm: authorization-api
  client-id: orchestrator-api
  client-secret: OY8dBw6hyng4oJL7LV10PAPivX113Yqx
  issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
user-service:
  url: http://localhost:8091/api/v1/individual


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer-uri}
